### ISSUE TITLE
Public Event Type Classification Use Case

### ISSUE THREAD

**Issue by ElenaShulman** [SEMICeu/Core-Public-Event-Vocabulary#14]
Hello! 

I thought the group would be interested to know that as part of the [EC's Digital Transformation programme](http://ec.europa.eu/ipg/basics/web_rationalisation/index_en.htm), DG COMM is developing an Event Content Type and that we have established a **Public Event Type** classification.  Although I have not mapped DG COMM’s Event Content Type to the Core Public Event model you have been developing,  I have mapped it to Schema.org 'Event' which is of course very close.  

Moreover, we are basing the definition of 'Public Event' on the definition you have established.  

The DG COMM's Public Event Type controlled vocabulary was developed through a series of workshops with other DGs and a harmonization of event type terms previously in use by a variety of EC websites.  

This vocabulary will be hosted by the [EUs Office of Publications Metadata Registry](http://publications.europa.eu/mdr/authority/index.html) and [European Union Open Data Portal](http://data.europa.eu/euodp/en/data/publisher/f85e1721-1db8-4db7-84c4-fc798731ed18?tags=authority+data) in a number of formats (it is not there yet).  This will be the authoritative ‘corporate’ controlled vocabulary to be used across the EC’s web presence.
 
I'm attaching the vocabulary here.
[Public Event Type.xlsx](https://github.com/SEMICeu/Core-Public-Event-Vocabulary/files/2184251/Public.Event.Type.xlsx)

Elena Shulman, PhD
Taxonomist

**Comment by akuckartz** [comment]
A minor suggestion: remove the redundant text "This concept includes" from the descriptions.

"Descrition" contains a typo.

**Comment by ElenaShulman** [comment]
Thanks!  The typo is in the field name label of the spreadsheet and will not impact the data.  I'm not convinced that the text you mention is redundant.

**Comment by sandervd** [comment]
Hi @ElenaShulman,

I'm really interested in the initiative, is the draft of the 'Event Content Type' ontology already accessible somewhere?

**Comment by ElenaShulman** [comment]
It is not accessible anywhere.  I can share it here in the coming weeks with the proviso that it may not be entirely stable.

**Comment by giorgialodi** [comment]
In Italy we have sketched a controlled vocabulary on the different types of Public Events and we have aligned it to schema.org. At the following repository https://github.com/italia/daf-ontologie-vocabolari-controllati/tree/master/VocabolariControllati/public-event-types you can find the vocabulary in excel, csv and in different RDF's serializations. In that repository you can also find the alignment to schema.org. BTW: you can navigate it via HTML too https://ontopia.daf.teamdigitale.it/lodview/controlled-vocabulary/public-event-types.html. At the moment, with a group of Italian Public Administrations we are slightly revising the vocabulary, also including definitions for each item. It could be particularly interesting understanding how to match this Italian vocabulary (that was done months ago where no vocabulary at the EU level was available) with what you are doing. It seems to me that there are things in common. 
Is the classification you shared the last version? Are you planning to extend it further?

BR,
Giorgia Lodi

**Comment by ElenaShulman** [comment]
@giorgialodi Oh, yes, there are definitely some obvious alignments between the two vocabularies.  We do not have plans to extend it in any significant way in the near future.   It can be considered a stable version.  Our vocabularies will, in general, be limited to what is needed for describing EC content and events organized in the context of the EC which would not include sports and many types of cultural or religious events I see in your list.  We can use [VocBench3](http://vocbench.uniroma2.it/), a vocabulary alignment tool from the EU Office of Publications to make the alignments when everything is ready.  What do you think?
Best,
Elena

**Comment by giorgialodi** [comment]
Dear @ElenaShulman thanks for your prompt reply. We started internally a discussion about this based on what you shared.  We definitely have other types of requirements to take into account. We have cultural events and sport events, if you think for instance to public events organized by municipalities. However, the events that are included in your list are surely part of the possibile set of events we need to take into account too. Therefore, we see two ways:
1) we can use either the vocabulary alignment tool you mention or constructs of the SKOS standard such as exactMatch, closeMatch, relatedMatch etc, in order to create links among the two vocabularies;
2) we can integrate, within the Italian controlled vocabulary, the items that are part of the taxonomy you shared.

Since the Italian controlled vocabulary was under revision, we opted for point number 2. In essence, the items you propose are part of the revised version of the Italian vocabulary that however will include also additional items. 
We may need your support at a certain moment in time in order to check whether we have correctly understood the semantic of your items.
BTW: can you clarify the role of the colums Successor and Predecessor in your excel file?

What do you think about this method?
We will definitely use this channel to share the result of our effort so that others interested in the works of this group can take inspiration or use it.

BR,
Giorgia

**Comment by ElenaShulman** [comment]
Dear @giorgialodi ,

I'm very glad to hear that you have been able to go with #2 since this cuts out complications with maintaining the alignments in the long term.  I'll be very glad to support you.  Feel free to ask when you need my input.  

As far as your question on the meaning of the columns Successor and Predecessor.  They reflect the vocabulary data model of the European Office of Publications and in this case they track any changes to the label of the concept.  See example [here](http://publications.europa.eu/mdr/resource/authority/resource-type/html/resourcetypes-eng.html) for a different vocab.  For the complete documentation [here](http://publications.europa.eu/mdr/resource/documentation/schema/cat.html)

Who will be using the vocabularies you are developing?

Best,

Elena

**Comment by cultureMatters** [comment]
Please, be kind to clarify :

Has the  blog  http://blogs.ec.europa.eu/eu-digital as part of the referred hyperlink  of the EC's Digital Transformation programme stopped evolving since 2016? If so, is it replaced by a new one? Should there exist an update procedure? Finally, is the **EC's digital Transformation Programme**  still active? Mr Kustor said -  Source : https://opengov.ellak.gr/2018/08/09/i-pili-tou-joinup-ena-ousiastiko-meso-gia-tis-kines-prospathies-ke-tin-epitichia-ton-kraton-melon-gia-tin-ilektroniki-diakivernisi/ - that the isa2 program will be followed by the "Program of digital Europe". Is this true? Thank you in advance; I m still trying to acclimatize to SEMIC...

**Comment by ElenaShulman** [comment]
@cultureMatters  The Digital Transformation Programme is active.  I am unable to answer any questions about ISA2 and I suggest you contact them [directly.](https://ec.europa.eu/isa2/how-contact-us_en).  I will pass along your question about a current source of information on the transformation to colleagues and will share their suggestions here. 

Best wishes,

Elena

**Comment by ElenaShulman** [comment]
The "public event type" vocabulary is now available here: http://publications.europa.eu/mdr/authority/public-event-type/index.html

**Comment by CharlineAlexandre** [comment]
During the past weeks, the SEMIC team has held bilateral discussions to work towards an official release of CPEV. Controlled vocabularies were discussed, particularly for 2 attributes: 
- Event type. The Publication Office and Ontopia already provide a classification.
- Audience type. 

Further discussion on this can be held here.

**Comment by EmidioStani** [comment]
Proposal to:

1) keep "eventType" property using the classification proposed by Publications Office: https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/public-event-type

2) add the property "audience" to classify the audience (skos:Concept), leaving to Member States how to implement such type of classification

**Comment by giorgialodi** [comment]
> Proposal to:
> 
>     1. keep "eventType" property using the classification proposed by Publications Office: https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/public-event-type

So we will have a very macro classification, right? In the sense that, looking at the vocabulary, each item typically includes a world of public events types :-)  Example: exhibition whose definition seems including cultural events (and to be honest, an exhibition seems to me a specific type of public event in the context of cultural events!).

**Comment by EmidioStani** [comment]
Hello @giorgialodi ,

that is the basis, then we could then provide input to the Publication Office to include additional classification

**Comment by giorgialodi** [comment]
Yep, I think it is the best thing to do. I mean, collect requirements in the use of this Core Voc by Member States, so that to propose changes at the EU vocabulary!

**Comment by williamverbeeck** [comment]
During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed to keep eventType and add audience property (How to implement this is up to the MS).
