### ISSUE TITLE
Unplanned events

### ISSUE THREAD

**Issue by CharlineAlexandre** [SEMICeu/Core-Public-Event-Vocabulary#17]
During the past weeks, the SEMIC team has held bilateral discussions to work towards an official release of CPEV.
It was discussed that events are not always scheduled or planned in advance. An event can just happen on the moment and be qualified as an event afterwards, e.g., terrorist attack. Such events should be one way or the other captured in the model. 

Further discussion on this can be held here.

**Comment by EmidioStani** [comment]
The proposal would be:

1) Like other Core Vocabularies, keep cardinalities open, so that restrictions on the timing of the events (start or end) do not exist
2) initially align to the definition proposed by the Publications Office:   https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/public-event-type,  thus to the respective event type

**Comment by williamverbeeck** [comment]
During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed to remove cardinalities in relations between DateTime and PubliEvent.
