### ISSUE TITLE
OpeningHourSpecification

### ISSUE THREAD

**Issue by CharlineAlexandre** [SEMICeu/Core-Public-Event-Vocabulary#20]
During the past weeks, the SEMIC team has held bilateral discussions to work towards an official release of CPEV.
It has been raised that OpeningHourSpecification is hard to deal with (e.g., events can happen at several times).

Further discussion on this can be held here.

**Comment by EmidioStani** [comment]
Proposal to add:

1) relation "hasTime" from PublicEvent to time:TemporalEntity (which allow to describe in details an period or an instant); the hasTime relation can reuse the time:hasTime URI
2) add property "description" in TemporatlEntity which allow to freely describe the time of the event
3) add relation "frequency" from TemporalEntity to skos:Concept to define the recurrence of the event. The URI of Frequency can be used from the Controlled Vocabulary Frequence of Publications Office: https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/frequency

**Comment by giorgialodi** [comment]
Hi @EmidioStani. Is this proposal to replace OpeningHoursSpecification? Because what you suggest here seems to me general on the time dimension of the public event. Opening hours was more related to the access conditions wrt the location where the Public Event takes place.

In any case, I like the proposal to have the concept of TemporalEntity asssociated with the Public Event in order to model its time dimension.  Not sure about the frequency: is it the frequency of the event? What do you mean with "the frequency of the TemporalEntity"? BTW: if the objective is to model recurrent events that happen with a specific frequency, there exists already [an ontology design pattern](http://ceur-ws.org/Vol-2459/pattern1.pdf) that can be taken into account as starting point (probably in the core voc, we just need a simplified version of it).

**Comment by EmidioStani** [comment]
Hello @giorgialodi ,

indeed the focus is on the time dimension of the event rather than on the opening of the location.

Yes it is the frequency of the event, the frequency property is not described in the Time Ontology, at least not so explicit like in iCalendar, so the proposal is to add it.
The idea is to give the possibility to specify recurrent events, like every day from 9am to 10am.
Looking at the document you shared I think we can at least benefit from:

-the relations "next event" and "previous event" to show a practical case of event related in a series (aside the parent) 
-the property "eventNumber": that is related to the issue #5 where we talk about Edition of event

**Comment by williamverbeeck** [comment]
During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed to:
- Use TemporalEntity.
- Add description and frequency property to TemporalEntity.
- Add hasNextEvent and hasPreviousEvent.
