### ISSUE TITLE
Existing solutions

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/Core-Public-Event-Vocabulary#3]
Which existing solutions should the Core Public Event Vocabulary take into account?

**Comment by brechtwyns** [comment]
Schema.org defines "event" as a certain time and location, such as a concert, lecture, or festival.
http://schema.org/Event

**Comment by sandervd** [comment]
Some open questions / things that come to mind...
It might be interesting to consider if  a 'Public event' is more specific than an 'Event'?
(In which case it could it be defined as a subclass of 'Event'?)
If not:
* Can all cases be covered by 'Event'? in which case, this might be used straight away, and simply 'endorsed' by Semic?
* If not all cases can be covered, to what extend would there be alignment/conflicts?
If it is more specific:
* Would it make sense to develop this within the W3C working group as a specific subclass?

**Comment by rtroncy** [comment]
[LODE](http://linkedevents.org/ontology/) is an ontology for Linking Open Descriptions of Events. Read [this paper](https://www.eurecom.fr/~troncy/Publications/Troncy_Shaw-aswc09.pdf) to have the design rationale of LODE which provides axioms to numerous other event-based ontologies such as CIDOC-CRM (used in Cultural Heritage), the [Simple Event Model (SEM)](http://semanticweb.cs.vu.nl/2009/11/sem/), the [Event Ontology](http://motools.sourceforge.net/event/event.html), EventsML (used by journalists) and Schema.org.

**Comment by cultureMatters** [comment]
This is Despina Plevria.
 I wonder if, studying the modelling data _after the webinar_, we could transfer here some of the knowledge being shared in the **chat** of the webinar. I only had time to copy the link for the document entitled "APPLICATION DES TECHNOLOGIES 3.0 À LA DESCRIPTION DES ÉVÉNEMENTS CULTURELS"; I missed the rest. 
And could you please refer to the modelled data  lists, for example the modelled data list showing types of Events (TheatreEvent etc). If possible..in order to help studying the _existing modelling endeavours /solutions on public events_, before creating use cases, as the schedule implies. Thank you!

**Comment by EmidioStani** [comment]
There are indeed different models, each with their views, complexity, etc; when possible the method is to reuse concepts by looking at their context, definitions, constraints 

Concerning type of events there is an initial list nf https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/public-event-type
