### ISSUE TITLE
Common definition for Public Event

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/Core-Public-Event-Vocabulary#6]
Dear all, with the Italian group participating in this working group we discussed a lot since the last call on the importance to:
1) have common definitions for public event and other elements that characterize it;
2) the importance to remember that we are creating something "core" that should be the "Minimum common denominator" across Member States (MSs), and that MSs can then specialize if required.

In this sense, one possibile definition can be the following (the definition captures, from our point of view, some basic elements that should be present in a core vocabulary on this domain): "_A public event is an event that takes places in a given place and that occurs at a certain time, organised/run by one or more agents with a specific purpose and in the interest of a general public. There exist different types of public events depending on their size and content_". The definiiton builds upon  the one available in the slides of the kickoff meeting with a few additional elements.
Talk to you tomorrow!

**Comment by FrancescaGleria** [comment]
Yes, together with the group i'm trying to work on it. I have a question for @EmidioStani  it could be useful to have a tools in order to organized proposal definition in a re-usable format.  I remember some table  you send us  for  the  "ontological cleaning". In the table there is  a column for "description", that table could be interesting for have a working tool tho share.  could you resent it to me ?  thanks. ... "because the frame is a good friend for thinking"

**Comment by EmidioStani** [comment]
Proposition:

“Something that happens at a particular place and time, organised by one or more agents for a particular purpose, and is of interest to a general public.
This definition excludes natural events such as earthquakes and volcanic eruptions.”

1) it aligns with Publications Office: https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/public-event-type
2) Doesn't use "An Event" at the beginning (using something because, it would need to specify what an Event means ([R2](https://github.com/SEMICeu/OpenGuidelines/blob/main/Principles%20for%20creating%20good%20definitions_v1.00.pdf)))
3) put "one or more agents" as Core Vocabularies do not apply restrictions
4) use the term "general public" instead of "audience": indicating any type of group of people instead of the people participating in the event.

This exclude non-public events as per issue #4

**Comment by williamverbeeck** [comment]
During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed to:
- Collect further comments and suggestions on the definition of PublicEvent
- Look at the definition by CIDOC CRM.

**Comment by EmidioStani** [comment]
CIDOC CRM includes only the concept of Event which differs from the concept of Public Event.

The final proposition is:

Something that happens at a particular place and time, organised by one or more agents for a particular purpose, and is of interest to a general audience.
