### ISSUE TITLE
Distinguishing active and passive participants

### ISSUE THREAD

**Issue by fvepwc** [SEMICeu/Core-Public-Event-Vocabulary#9]
During the last webinar, there was a discussion on whether and how active and passive participants of an event should be modeled. This is what was said on this during the webinar:

Should we make a distinction between active and passive participants? For instance the difference between performers and attendees at a concert?

- The distinction is made in many models.
- Several of these properties are already in schema.org. We may want to cluster together. We can maybe subclass the general event when we need to add more information. Do we want to model differently for shows, summits etc. This is related to what should be included in a core data model.
  - Be wary that we are defining a core model. We need a minimum common denominator, not too much detail. We should not try to model every possible situation.
  - The idea of subClassing could be that you want to further define (i.e. classify) events, e.g. mandating that some events MUST have a value for this property, or to say it differently, if such a property is valued, then the machine infers that this is a special type of events
  - How does subclassing help out on top of what already exists through optional fields?
- We could use several relation to the Agent class to model these different roles.

Further discussions on this can be held here.

**Comment by cultureMatters** [comment]
I think that this information, as most  details, should be held (recorded) ONCE in the model, and noted clearly.
 I assume that maybe we should consider that Artificial Intelligence (for example 'planning') should be used at one schema above the model, for better recognition of its functionality. I' m not very sure about that, it is just an idea; to be frank I m still reading the PROCESS AND METHODOLOGY FOR CORE
VOCABULARIES, in order to clarify the flexibility factor that the core public event vocabulary should have.
Thank you.

**Comment by CharlineAlexandre** [comment]
During the past weeks, the SEMIC team has held bilateral discussions to work towards an official release of CPEV.
A point that was raised during the discussions is the importance of distinguishing between the different participant roles as well as the need to distinguish between the event publisher, who is advertising the event and participants planning to attend the event.
Some propositions of roles are the following: organizer, speaker, participants, target audience. 

Further discussion on this can be held here.

**Comment by MarcOlie** [comment]
prov:Role, and the implementation for DataSet contributors in DCAT with Qualified relations can work for this. With a qualified relation also other information can be added, e.g. only partial attendance, or maybe online/in person attendance etc

**Comment by EmidioStani** [comment]
As there can be different roles for different types of public event, the proposal indeed is to

1) capture the concept of participants within a Role class 
2) add "name" to indicate a label for it.
3) links the Event class to the Role class by a relation "hasRole", to indicate Role associated to the Event
4) link the Agent class to the Role class by a relation "playsRole", to indicate the Agent associated to the Event
5) the definition of Role could resemble to "The function occupied by an agent in a certain context" where, in this case, the context is the Public Event and the function could be one of the above mentioned roles. In this way the concept could be reused in other Core Vocabularies and contexts.

Having said that, we notice that:
1) until now the timing associated to a Role is not considered however, if we consider the concept of "speaker" or somebody performing an exhibitions or a training, we can think it might have associated to a time slot.
2) leaving Role as generic class would keep it open for Member States implementing accordingly to their requirements.  
3) There are different standards out including the concept of Role having their definitions in their own scope.
In particular, in the [PROV-O](https://www.w3.org/TR/prov-o/#Role) ontology mentioned above, the definition is quite complex: "function of an entity or agent with respect to an activity, in the context of a usage, generation, invalidation, association, start, and end" where entity, agent and activity are defined with PROV ontology.

**Comment by giorgialodi** [comment]
I am not sure this modelling works. If you want to indicate an agent with a role participating in a public event you need to have a reification (participation) that links the three involved entities.

**Comment by EmidioStani** [comment]
Thanks Giorgia for the suggestion, it is a proposal at this point in time. Another possibility indeed is using a similar approach like in CPSV-AP (having the Participation class in the middle between Agent and Public Service)

**Comment by giorgialodi** [comment]
> Thanks Giorgia for the suggestion, it is a proposal at this point in time. Another possibility indeed is using a similar approach like in CPSV-AP (having the Participation class in the middle between Agent and Public Service)

Exactly! BTW: if you reuse the same modelling pattern you can have better interoperability across core vocs :)

**Comment by williamverbeeck** [comment]
During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed to:
- Reuse Participation class from CPSV-AP including the concept role. (Option add hasTime relation for the timing of the Participation)
- Review the direction of the relation between Agent and Participation

**Comment by EmidioStani** [comment]
This issue is related to: https://github.com/SEMICeu/CPSV-AP/issues/110

**Comment by jpmckinney** [comment]
The answer to the issue description is not clear in the public documentation.

A very common use case is to determine the organizer of an event. For example, schema.org has https://schema.org/organizer

I would not typically expect to find the organizer among the participants. Notably:

1) An organizer is often an organization rather than a person. For example, a church can organize a holiday hamper. (While, in reality, individual people would be involved in the event's organization, they are rarely identified in real-world data.) It seems unusual to label an organization as a "participant" in scenarios like this.
2) There are many events in which an organizer does not participate, such that the term "participant" is inappropriate to the organizer. For example, a leader of a social club might organize an outing for its members, but not actually attend the outing themselves (conflicting schedules, etc.). It seems unnatural to label the organizer as a "participant" in the event.

I can open a new issue if appropriate.

Edit: If it's desired to put all agents into one property, then a generic label like "agents" would be more appropriate than a term with narrower semantic like "participants".
